### ISSUE TITLE
Support the GitHub Action "debug logging" feature

### ISSUE THREAD

**Issue by lionello** [DefangLabs/defang-github-action#8]
![image](https://github.com/user-attachments/assets/0bc4c158-5d12-4ff4-9461-f9e04eb89757)

When re-running an action, checking the "debug logging" box should add `--debug` to the defang command line.

See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/troubleshooting-workflows/enabling-debug-logging

**Comment by raphaeltm** [comment]
Neat. I didn't realize that was a feature GitHub had.
